# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['Main.py'],
    pathex=[r'D:\coding project\RustyBot V1.2 GUI and new Draw\Rusty Bot Main Branch - 1.36 - fixed'],
    binaries=[],
    datas=[
        ('assets/animation.html', 'assets'),
        ('assets/mini_test.html', 'assets'),
        ('assets/portrait_test.html', 'assets'),
        ('assets/script.js', 'assets'),
        ('assets/background_lists.js', 'assets'),
        ('assets/network_animation.js', 'assets'),
        ('assets/qwebchannel.js', 'assets'),
        ('assets/style.css', 'assets'),
        ('icon.ico', '.'),
        ('Loading.png', '.'),
        ('loading_init.png', '.'),
        ('RUSTY BOT.png', '.'),
        ('Fonts/Shentox-SemiBold.ttf', 'Fonts'),
        ('Fonts/triglavian-complete.otf', 'Fonts'),
        ('sounds/44.wav', 'sounds'),
        ('sounds/Background.mp3', 'sounds'),
        ('sounds/bk.wav', 'sounds'),
        ('sounds/countdown.wav', 'sounds'),
        ('sounds/Fail.wav', 'sounds'),
        ('sounds/Hacking in progress.mp3', 'sounds'),
        ('sounds/Notification.mp3', 'sounds'),
        ('sounds/Reel_Loop.wav', 'sounds'),
        ('sounds/stop R1.wav', 'sounds'),
        ('sounds/tick-sound-effect-1-336779.mp3', 'sounds'),
        ('sounds/Timer_Armor.mp3', 'sounds'),
        ('sounds/Timer_Hull.mp3', 'sounds'),
        ('sounds/Timer_Shield.mp3', 'sounds'),
        ('sounds/verified.wav', 'sounds'),
        ('sounds/wheel_tick.wav', 'sounds'),
        ('sounds/Winner_Selected.wav', 'sounds'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='RustyBot_Main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icon.ico'],
)
